#!/bin/sh
# Copyright (c) 2004-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Contributed by Roy Marples (uberlord@gentoo.org)

# Map the dns, ntp and nis info so our system module can apply the setup

export dns_domain_${interface}="${domain}"
export dns_servers_${interface}="${dns}"

export ntp_servers_${interface}="${ntpsrv}"

export nis_domain_${interface}="${nisdomain}"
export nis_servers_${interface}="${nissrv}"

# This is a hack
export INITNG_PLUGIN_DIR=/lib/initng

${INITNG_PLUGIN_DIR}/scripts/net/dhcp "$@"
